DEBUG = False
TESTING = False

SERVER_HOST_NAME = 'login.hellodocs.com'
SERVER_PORT = 5000
SERVER_NAME = SERVER_HOST_NAME + ':' + str(SERVER_PORT)

MAX_CONTENT_LENGTH = 1048576

SQLALCHEMY_DB_ECHO = True

WORKFLOW_COOKIE_NAME = 'w_s'
